import type { Project, ProjectMeta } from '@/types';

export function createSampleProject(): Project {
  const meta: ProjectMeta = {
    id: 'sample-cloud-migration',
    name: 'AWS Cloud Migration',
    description: 'Migrate legacy on-premises infrastructure to AWS for improved scalability, reliability, and cost optimization',
    status: 'active',
    health: 'amber',
    startDate: '2026-01-15',
    targetEndDate: '2026-09-30',
    jiraBoardId: '',
    jiraBoardName: '',
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-03-13T14:30:00Z',
  };

  return {
    meta,
    charter: {
      documentVersion: '1.2',
      documentOwner: 'Kwame Mensah',
      issueDate: '2026-01-12',
      executiveSummary: 'This project charter authorises the AWS Cloud Migration initiative to migrate all on-premises production workloads to Amazon Web Services by September 30, 2026. The project is driven by an expiring data centre lease and an organisational mandate to achieve cloud-native operations. Key risks include the billing system refactoring requirement and team AWS skills readiness. Budget is approved at $450,000 and the project is currently tracking AMBER due to one invalidated assumption (App #7 containerisation).',
      projectPurpose: 'To migrate 12 production applications and supporting infrastructure from an end-of-life on-premises data centre to AWS, reducing operational costs by 40%, improving resilience to 99.99% uptime SLA, and enabling engineering teams to self-serve infrastructure through CI/CD and auto-scaling.',
      vision: 'Fully cloud-native infrastructure on AWS by Q3 2026, enabling 99.99% uptime, 40% cost reduction, and auto-scaling for peak traffic.',
      objectives: [
        'Migrate all production workloads to AWS by September 2026',
        'Achieve 99.99% uptime SLA for critical services',
        'Reduce infrastructure costs by 40% compared to on-premises',
        'Implement auto-scaling for all customer-facing applications',
        'Establish CI/CD pipelines for all migrated services',
      ],
      businessObjectives: [
        'Reduce infrastructure costs by 40% post-migration (target: <$15,000/month)',
        'Eliminate data centre lease dependency before October 2026 deadline',
        'Improve service availability from 99.5% to 99.99% SLA',
        'Enable engineering team self-service for infrastructure provisioning',
      ],
      technologyObjectives: [
        'Deploy all 12 applications to AWS EKS (Kubernetes)',
        'Migrate PostgreSQL to Amazon Aurora, MongoDB to DocumentDB, Redis to ElastiCache',
        'Implement CI/CD pipelines via GitHub Actions for all migrated services',
        'Set up CloudWatch + Grafana monitoring stack on AWS',
        'Configure VPC, security groups, and IAM roles per SOC 2 requirements',
      ],
      scope: 'Migration of 12 production applications, 3 databases (PostgreSQL, MongoDB, Redis), networking infrastructure, monitoring stack, and CI/CD pipelines from on-premises data center to AWS.',
      outOfScope: 'Desktop applications, legacy mainframe systems, physical office network infrastructure, end-user device management.',
      assumptions: [
        'AWS account and landing zone will be provisioned by IT Ops by Feb 2026',
        'Development team has basic AWS certification or training',
        'Current application architectures support containerization',
        'Budget approved for Q1-Q3 2026',
      ],
      constraints: [
        'Zero downtime for customer-facing services during migration',
        'Must comply with SOC 2 and GDPR requirements',
        'Migration must complete before data center lease expires Oct 2026',
        'Budget cap of $450,000 for migration activities',
      ],
      qualityStandards: [
        'All migrated services must pass automated health checks before go-live',
        'Zero data loss tolerance — 100% data fidelity verified via checksums',
        'All infrastructure provisioned via Terraform (Infrastructure as Code)',
        'Security review required before each application goes live in production',
        'Load testing required at 2x expected peak traffic before cutover',
      ],
      qualityAssurance: 'Quality assurance is managed through a combination of automated testing (unit, integration, E2E), security scanning (Snyk, AWS Security Hub), and manual review gates at each phase milestone. All changes require peer review and sign-off from the Tech Lead before deployment to production.',
      successCriteria: [
        'All 12 applications running on AWS with <50ms latency increase',
        'Infrastructure costs below $15,000/month post-migration',
        'Zero data loss during migration',
        'All services passing automated health checks',
        'Team fully trained on AWS operations',
      ],
      sponsors: ['Sarah Chen (CTO)', 'Marcus Williams (VP Engineering)'],
      approvals: [
        { id: 'appr-001', role: 'Project Sponsor', name: 'Sarah Chen', date: '2026-01-12', status: 'approved' },
        { id: 'appr-002', role: 'Project Review Group', name: 'Marcus Williams', date: '2026-01-12', status: 'approved' },
        { id: 'appr-003', role: 'Project Manager', name: 'Kwame Mensah', date: '2026-01-10', status: 'approved' },
        { id: 'appr-004', role: 'Quality Manager', name: 'Aisha Thompson', date: '2026-01-15', status: 'approved' },
        { id: 'appr-005', role: 'Communications Manager', name: 'David Osei', date: '', status: 'pending' },
        { id: 'appr-006', role: 'Procurement Manager', name: '', date: '', status: 'pending' },
      ],
      approvalDate: '2026-01-15',
    },
    plan: {
      purpose: 'This project plan outlines the phased migration of our on-premises infrastructure to AWS, covering scope, schedule, budget, governance, and risk management.',
      goals: [
        'Complete discovery and assessment of all workloads',
        'Design cloud-native architecture for each application',
        'Execute migration with zero customer impact',
      ],
      deliverables: [
        { id: 'd1', name: 'Cloud Architecture Design', description: 'Target architecture for all 12 applications on AWS', acceptanceCriteria: 'Reviewed and approved by architecture board', dueDate: '2026-02-28', status: 'accepted' },
        { id: 'd2', name: 'Migration Runbooks', description: 'Step-by-step migration procedures for each application', acceptanceCriteria: 'Tested in staging environment', dueDate: '2026-03-31', status: 'in-progress' },
        { id: 'd3', name: 'Monitoring Dashboard', description: 'CloudWatch-based monitoring for all migrated services', acceptanceCriteria: 'Alerts configured for all critical metrics', dueDate: '2026-04-30', status: 'pending' },
        { id: 'd4', name: 'DR Plan', description: 'Disaster recovery procedures for AWS environment', acceptanceCriteria: 'Tested with simulated failover', dueDate: '2026-06-30', status: 'pending' },
        { id: 'd5', name: 'Cost Optimization Report', description: 'Final cost analysis comparing on-prem vs AWS', acceptanceCriteria: 'Shows >=35% cost reduction', dueDate: '2026-09-15', status: 'pending' },
      ],
      milestones: [
        { id: 'm1', name: 'Discovery & Assessment Complete', dueDate: '2026-02-15', status: 'completed' },
        { id: 'm2', name: 'Architecture Design Approved', dueDate: '2026-02-28', status: 'completed' },
        { id: 'm3', name: 'Staging Environment Ready', dueDate: '2026-03-15', status: 'on-track' },
        { id: 'm4', name: 'First Application Migrated (Auth Service)', dueDate: '2026-04-15', status: 'upcoming' },
        { id: 'm5', name: 'Database Migration Complete', dueDate: '2026-06-01', status: 'upcoming' },
        { id: 'm6', name: 'All Applications Migrated', dueDate: '2026-08-15', status: 'upcoming' },
        { id: 'm7', name: 'On-Prem Decommission', dueDate: '2026-09-15', status: 'upcoming' },
        { id: 'm8', name: 'Project Closure', dueDate: '2026-09-30', status: 'upcoming' },
      ],
      budget: [
        { id: 'b1', category: 'AWS Infrastructure (9 months)', planned: 120000, actual: 28000, variance: -92000 },
        { id: 'b2', category: 'Migration Tools & Licensing', planned: 35000, actual: 32000, variance: -3000 },
        { id: 'b3', category: 'External Consulting', planned: 80000, actual: 45000, variance: -35000 },
        { id: 'b4', category: 'Team Training & Certification', planned: 25000, actual: 22000, variance: -3000 },
        { id: 'b5', category: 'Contingency Reserve', planned: 45000, actual: 0, variance: -45000 },
        { id: 'b6', category: 'Testing & QA', planned: 30000, actual: 12000, variance: -18000 },
      ],
      qualityStandards: [
        'All services must pass load testing at 2x peak traffic',
        'Security scan with zero critical/high findings before go-live',
        'API response times within 10% of on-prem baseline',
        'Automated test coverage >= 80% for migrated services',
      ],
      procurementNeeds: [
        'AWS Enterprise Support Plan',
        'Datadog monitoring license (12 months)',
        'HashiCorp Terraform Cloud Team subscription',
        'AWS Migration Acceleration Program (MAP) credits',
      ],
    },
    gantt: {
      tasks: [
        { id: 'g1', name: 'Discovery & Assessment', startDate: '2026-01-15', endDate: '2026-02-15', progress: 100, assignee: 'James Park', dependencies: [], color: '#3b82f6' },
        { id: 'g2', name: 'Architecture Design', startDate: '2026-02-01', endDate: '2026-02-28', progress: 100, assignee: 'Priya Sharma', dependencies: ['g1'], color: '#3b82f6' },
        { id: 'g3', name: 'AWS Landing Zone Setup', startDate: '2026-02-15', endDate: '2026-03-15', progress: 75, assignee: 'Alex Rivera', dependencies: ['g2'], color: '#f59e0b' },
        { id: 'g4', name: 'CI/CD Pipeline Setup', startDate: '2026-03-01', endDate: '2026-03-31', progress: 50, assignee: 'James Park', dependencies: ['g3'], color: '#f59e0b' },
        { id: 'g5', name: 'Auth Service Migration', startDate: '2026-03-15', endDate: '2026-04-15', progress: 20, assignee: 'Priya Sharma', dependencies: ['g3'], color: '#ef4444' },
        { id: 'g6', name: 'API Gateway Migration', startDate: '2026-04-01', endDate: '2026-05-01', progress: 0, assignee: 'Alex Rivera', dependencies: ['g5'], color: '#6b7280' },
        { id: 'g7', name: 'Database Migration (PostgreSQL)', startDate: '2026-04-15', endDate: '2026-05-31', progress: 0, assignee: 'David Kim', dependencies: ['g5'], color: '#6b7280' },
        { id: 'g8', name: 'Database Migration (MongoDB)', startDate: '2026-05-01', endDate: '2026-06-01', progress: 0, assignee: 'David Kim', dependencies: ['g7'], color: '#6b7280' },
        { id: 'g9', name: 'Remaining Apps Migration', startDate: '2026-05-15', endDate: '2026-08-01', progress: 0, assignee: 'Full Team', dependencies: ['g6', 'g7'], color: '#6b7280' },
        { id: 'g10', name: 'Performance Testing', startDate: '2026-07-15', endDate: '2026-08-15', progress: 0, assignee: 'QA Team', dependencies: ['g9'], color: '#6b7280' },
        { id: 'g11', name: 'On-Prem Decommission', startDate: '2026-08-15', endDate: '2026-09-15', progress: 0, assignee: 'Alex Rivera', dependencies: ['g10'], color: '#6b7280' },
      ],
    },
    wbs: [
      {
        id: 'w1', name: '1. Initiation', description: 'Project kickoff and planning', children: [
          { id: 'w1.1', name: '1.1 Stakeholder Alignment', description: '', children: [], linkedTaskIds: [] },
          { id: 'w1.2', name: '1.2 Discovery & Assessment', description: '', children: [], linkedTaskIds: ['g1'] },
          { id: 'w1.3', name: '1.3 Architecture Design', description: '', children: [], linkedTaskIds: ['g2'] },
        ], linkedTaskIds: [],
      },
      {
        id: 'w2', name: '2. Foundation', description: 'AWS environment setup', children: [
          { id: 'w2.1', name: '2.1 Landing Zone', description: '', children: [], linkedTaskIds: ['g3'] },
          { id: 'w2.2', name: '2.2 Networking (VPC/VPN)', description: '', children: [], linkedTaskIds: [] },
          { id: 'w2.3', name: '2.3 Security Baseline', description: '', children: [], linkedTaskIds: [] },
          { id: 'w2.4', name: '2.4 CI/CD Pipelines', description: '', children: [], linkedTaskIds: ['g4'] },
        ], linkedTaskIds: [],
      },
      {
        id: 'w3', name: '3. Migration Execution', description: 'Application and data migration', children: [
          { id: 'w3.1', name: '3.1 Auth Service', description: '', children: [], linkedTaskIds: ['g5'] },
          { id: 'w3.2', name: '3.2 API Gateway', description: '', children: [], linkedTaskIds: ['g6'] },
          { id: 'w3.3', name: '3.3 Databases', description: '', children: [], linkedTaskIds: ['g7', 'g8'] },
          { id: 'w3.4', name: '3.4 Remaining Applications', description: '', children: [], linkedTaskIds: ['g9'] },
        ], linkedTaskIds: [],
      },
      {
        id: 'w4', name: '4. Validation & Closure', description: 'Testing and handover', children: [
          { id: 'w4.1', name: '4.1 Performance Testing', description: '', children: [], linkedTaskIds: ['g10'] },
          { id: 'w4.2', name: '4.2 Security Audit', description: '', children: [], linkedTaskIds: [] },
          { id: 'w4.3', name: '4.3 Decommission', description: '', children: [], linkedTaskIds: ['g11'] },
          { id: 'w4.4', name: '4.4 Project Closure', description: '', children: [], linkedTaskIds: [] },
        ], linkedTaskIds: [],
      },
    ],
    raci: {
      roles: [
        { id: 'r1', name: 'Sarah Chen', title: 'CTO / Sponsor' },
        { id: 'r2', name: 'You (PM)', title: 'Project Manager' },
        { id: 'r3', name: 'Priya Sharma', title: 'Lead Architect' },
        { id: 'r4', name: 'James Park', title: 'DevOps Lead' },
        { id: 'r5', name: 'Alex Rivera', title: 'Cloud Engineer' },
        { id: 'r6', name: 'David Kim', title: 'DBA' },
      ],
      activities: [
        { id: 'a1', name: 'Architecture Design', category: 'Planning' },
        { id: 'a2', name: 'Budget Approval', category: 'Governance' },
        { id: 'a3', name: 'Landing Zone Setup', category: 'Foundation' },
        { id: 'a4', name: 'CI/CD Pipeline', category: 'Foundation' },
        { id: 'a5', name: 'App Migration', category: 'Execution' },
        { id: 'a6', name: 'DB Migration', category: 'Execution' },
        { id: 'a7', name: 'Security Audit', category: 'Validation' },
        { id: 'a8', name: 'Performance Testing', category: 'Validation' },
      ],
      matrix: {
        a1: { r1: 'A', r2: 'C', r3: 'R', r4: 'C', r5: 'C', r6: 'I' },
        a2: { r1: 'A', r2: 'R', r3: 'C', r4: 'I', r5: 'I', r6: 'I' },
        a3: { r1: 'I', r2: 'A', r3: 'C', r4: 'R', r5: 'R', r6: 'I' },
        a4: { r1: 'I', r2: 'A', r3: 'C', r4: 'R', r5: 'C', r6: 'I' },
        a5: { r1: 'I', r2: 'A', r3: 'R', r4: 'C', r5: 'R', r6: 'C' },
        a6: { r1: 'I', r2: 'A', r3: 'C', r4: 'I', r5: 'C', r6: 'R' },
        a7: { r1: 'A', r2: 'R', r3: 'C', r4: 'C', r5: 'C', r6: 'C' },
        a8: { r1: 'I', r2: 'A', r3: 'C', r4: 'R', r5: 'R', r6: 'C' },
      },
    },
    risks: [
      { id: 'risk1', title: 'Data loss during database migration', description: 'Large datasets may have corruption or loss during transfer', category: 'Technical', probability: 2, impact: 5, severity: 10, owner: 'David Kim', mitigationStrategy: 'Full backups before migration, row-count validation, parallel running period', contingencyPlan: 'Restore from backup and retry', status: 'mitigating', linkedWbsIds: ['w3.3'], linkedTaskIds: ['g7', 'g8'], createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-03-10T15:00:00Z' },
      { id: 'risk2', title: 'Exceeding migration budget', description: 'AWS costs may exceed estimates during parallel running', category: 'Financial', probability: 3, impact: 4, severity: 12, owner: 'You (PM)', mitigationStrategy: 'Weekly cost monitoring, AWS Cost Explorer alerts, Reserved Instances for known workloads', contingencyPlan: 'Use contingency reserve, optimize instance sizes', status: 'open', linkedWbsIds: [], linkedTaskIds: [], createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-03-10T15:00:00Z' },
      { id: 'risk3', title: 'Extended downtime during cutover', description: 'DNS propagation and service switchover may cause outage', category: 'Operational', probability: 3, impact: 5, severity: 15, owner: 'James Park', mitigationStrategy: 'Blue-green deployment, pre-warmed environments, low-TTL DNS records', contingencyPlan: 'Immediate rollback to on-prem with DNS switch', status: 'open', linkedWbsIds: ['w3.1'], linkedTaskIds: ['g5'], createdAt: '2026-01-25T10:00:00Z', updatedAt: '2026-03-10T15:00:00Z' },
      { id: 'risk4', title: 'Team AWS skills gap', description: 'Team may lack deep AWS expertise for complex migrations', category: 'People', probability: 4, impact: 3, severity: 12, owner: 'Priya Sharma', mitigationStrategy: 'AWS training program, pair programming with consultant, architecture reviews', contingencyPlan: 'Extend consulting engagement', status: 'mitigating', linkedWbsIds: [], linkedTaskIds: [], createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-28T15:00:00Z' },
      { id: 'risk5', title: 'Third-party dependency incompatibility', description: 'Some vendor APIs may not work with AWS networking', category: 'Technical', probability: 2, impact: 3, severity: 6, owner: 'Alex Rivera', mitigationStrategy: 'Vendor compatibility audit, early testing in staging', contingencyPlan: 'API gateway proxy or VPN tunnel', status: 'open', linkedWbsIds: ['w3.4'], linkedTaskIds: ['g9'], createdAt: '2026-02-10T10:00:00Z', updatedAt: '2026-03-10T15:00:00Z' },
      { id: 'risk6', title: 'SOC 2 compliance gap in AWS config', description: 'AWS environment may not meet all SOC 2 controls initially', category: 'Compliance', probability: 3, impact: 4, severity: 12, owner: 'You (PM)', mitigationStrategy: 'AWS Config rules, automated compliance checks, pre-audit review', contingencyPlan: 'Engage compliance consultant for remediation', status: 'open', linkedWbsIds: ['w4.2'], linkedTaskIds: [], createdAt: '2026-02-15T10:00:00Z', updatedAt: '2026-03-10T15:00:00Z' },
    ],
    issues: [
      { id: 'iss1', title: 'VPN tunnel intermittent disconnections', description: 'Site-to-site VPN between on-prem and AWS drops every 2-3 hours', priority: 'high', owner: 'Alex Rivera', status: 'in-progress', resolution: '', dueDate: '2026-03-20', createdAt: '2026-03-05T10:00:00Z', updatedAt: '2026-03-12T10:00:00Z' },
      { id: 'iss2', title: 'Terraform state file locking conflicts', description: 'Multiple engineers hitting state lock errors during concurrent applies', priority: 'medium', owner: 'James Park', status: 'resolved', resolution: 'Migrated to Terraform Cloud with remote state and auto-locking', dueDate: '2026-03-10', createdAt: '2026-03-01T10:00:00Z', updatedAt: '2026-03-08T10:00:00Z' },
      { id: 'iss3', title: 'AWS service quota limit for EC2 instances', description: 'Default vCPU limit too low for staging + production environments', priority: 'high', owner: 'Alex Rivera', status: 'open', resolution: '', dueDate: '2026-03-18', createdAt: '2026-03-10T10:00:00Z', updatedAt: '2026-03-10T10:00:00Z' },
      { id: 'iss4', title: 'Legacy app uses hardcoded IP addresses', description: 'Payment service has hardcoded DB IP that won\'t work after migration', priority: 'critical', owner: 'Priya Sharma', status: 'in-progress', resolution: '', dueDate: '2026-03-25', createdAt: '2026-03-08T10:00:00Z', updatedAt: '2026-03-12T10:00:00Z' },
    ],
    changes: {
      log: [
        { id: 'cl1', version: '1.0', date: '2026-01-15', description: 'Initial project plan approved', author: 'You (PM)' },
        { id: 'cl2', version: '1.1', date: '2026-02-10', description: 'Added MongoDB migration to scope', author: 'Priya Sharma' },
        { id: 'cl3', version: '1.2', date: '2026-03-01', description: 'Extended Phase 2 timeline by 2 weeks due to VPN issues', author: 'You (PM)' },
      ],
      requests: [
        { id: 'cr1', name: 'Add Redis migration to scope', requestedBy: 'David Kim', date: '2026-03-08', description: 'Redis cache cluster should be migrated to ElastiCache alongside PostgreSQL', reason: 'Performance dependency — apps need Redis for session management', priority: 'high', impactOnDeliverables: 'Adds 1 week to database migration phase', costEvaluation: '+$3,000 for ElastiCache monthly', riskEvaluation: 'Low risk — straightforward migration', qualityEvaluation: 'No impact', durationImpact: '+1 week', status: 'accepted', approverComments: 'Approved — critical for app performance', linkedRiskIds: [] },
        { id: 'cr2', name: 'Switch from ECS to EKS', requestedBy: 'Priya Sharma', date: '2026-03-12', description: 'Use Kubernetes (EKS) instead of ECS for container orchestration', reason: 'Team has more K8s experience, better multi-cloud portability', priority: 'medium', impactOnDeliverables: 'Requires architecture redesign for container services', costEvaluation: '+$5,000/month for EKS control plane', riskEvaluation: 'Medium — more complexity but team is experienced', qualityEvaluation: 'Better long-term maintainability', durationImpact: '+2 weeks for re-architecture', status: 'pending', approverComments: '', linkedRiskIds: ['risk4'] },
      ],
    },
    resources: [
      { id: 'res1', name: 'You (PM)', role: 'Project Manager', email: 'pm@company.com', allocationPercent: 100, costRate: 95, assignedTaskIds: [], availability: 'available' },
      { id: 'res2', name: 'Priya Sharma', role: 'Lead Architect', email: 'priya@company.com', allocationPercent: 80, costRate: 120, assignedTaskIds: ['g2', 'g5'], availability: 'available' },
      { id: 'res3', name: 'James Park', role: 'DevOps Lead', email: 'james@company.com', allocationPercent: 100, costRate: 110, assignedTaskIds: ['g1', 'g4'], availability: 'available' },
      { id: 'res4', name: 'Alex Rivera', role: 'Cloud Engineer', email: 'alex@company.com', allocationPercent: 100, costRate: 100, assignedTaskIds: ['g3', 'g6', 'g11'], availability: 'available' },
      { id: 'res5', name: 'David Kim', role: 'Database Administrator', email: 'david@company.com', allocationPercent: 60, costRate: 105, assignedTaskIds: ['g7', 'g8'], availability: 'partial' },
      { id: 'res6', name: 'AWS Consultant (External)', role: 'Cloud Consultant', email: 'consultant@partner.com', allocationPercent: 40, costRate: 200, assignedTaskIds: [], availability: 'partial' },
    ],
    estimates: [
      { id: 'e1', phase: 'Discovery', item: 'Application assessment (12 apps)', hours: 120, rate: 110, materialCost: 0, total: 13200 },
      { id: 'e2', phase: 'Foundation', item: 'Landing Zone & VPC setup', hours: 80, rate: 110, materialCost: 5000, total: 13800 },
      { id: 'e3', phase: 'Foundation', item: 'CI/CD pipeline configuration', hours: 60, rate: 110, materialCost: 2000, total: 8600 },
      { id: 'e4', phase: 'Migration', item: 'Application containerization', hours: 200, rate: 115, materialCost: 0, total: 23000 },
      { id: 'e5', phase: 'Migration', item: 'Database migration (3 DBs)', hours: 160, rate: 105, materialCost: 3000, total: 19800 },
      { id: 'e6', phase: 'Migration', item: 'DNS & networking cutover', hours: 40, rate: 110, materialCost: 0, total: 4400 },
      { id: 'e7', phase: 'Validation', item: 'Performance & load testing', hours: 80, rate: 100, materialCost: 5000, total: 13000 },
      { id: 'e8', phase: 'Validation', item: 'Security audit & remediation', hours: 60, rate: 120, materialCost: 10000, total: 17200 },
      { id: 'e9', phase: 'Closure', item: 'On-prem decommission', hours: 40, rate: 100, materialCost: 0, total: 4000 },
    ],
    kpis: [
      { id: 'k1', name: 'Applications Migrated', category: 'Progress', target: 12, actual: 0, unit: 'apps', trend: [{ date: '2026-01', value: 0 }, { date: '2026-02', value: 0 }, { date: '2026-03', value: 0 }], status: 'on-track' },
      { id: 'k2', name: 'Budget Utilization', category: 'Financial', target: 450000, actual: 139000, unit: '$', trend: [{ date: '2026-01', value: 25000 }, { date: '2026-02', value: 85000 }, { date: '2026-03', value: 139000 }], status: 'on-track' },
      { id: 'k3', name: 'Open High-Severity Risks', category: 'Risk', target: 0, actual: 3, unit: 'risks', trend: [{ date: '2026-01', value: 2 }, { date: '2026-02', value: 4 }, { date: '2026-03', value: 3 }], status: 'at-risk' },
      { id: 'k4', name: 'Team AWS Certifications', category: 'People', target: 5, actual: 3, unit: 'certs', trend: [{ date: '2026-01', value: 1 }, { date: '2026-02', value: 2 }, { date: '2026-03', value: 3 }], status: 'on-track' },
      { id: 'k5', name: 'Uptime (Migrated Services)', category: 'Quality', target: 99.99, actual: 99.95, unit: '%', trend: [{ date: '2026-02', value: 99.9 }, { date: '2026-03', value: 99.95 }], status: 'at-risk' },
      { id: 'k6', name: 'Sprint Velocity', category: 'Delivery', target: 40, actual: 35, unit: 'pts/sprint', trend: [{ date: 'Sprint 1', value: 28 }, { date: 'Sprint 2', value: 32 }, { date: 'Sprint 3', value: 35 }], status: 'on-track' },
    ],
    roadmap: [
      { id: 'rm1', feature: 'AWS Landing Zone', description: 'Multi-account structure with security baseline', quarter: 'Q1 2026', status: 'completed', priority: 'critical', swimlane: 'Infrastructure' },
      { id: 'rm2', feature: 'CI/CD on AWS', description: 'CodePipeline + CodeBuild for all services', quarter: 'Q1 2026', status: 'in-progress', priority: 'high', swimlane: 'Infrastructure' },
      { id: 'rm3', feature: 'Auth Service Migration', description: 'First app migration — OAuth2 service to ECS', quarter: 'Q2 2026', status: 'planned', priority: 'critical', swimlane: 'Applications' },
      { id: 'rm4', feature: 'Database Migration', description: 'PostgreSQL to RDS, MongoDB to DocumentDB', quarter: 'Q2 2026', status: 'planned', priority: 'critical', swimlane: 'Data' },
      { id: 'rm5', feature: 'Remaining Apps (10)', description: 'Batch migration of remaining services', quarter: 'Q3 2026', status: 'planned', priority: 'high', swimlane: 'Applications' },
      { id: 'rm6', feature: 'Monitoring & Observability', description: 'CloudWatch + Datadog integration', quarter: 'Q2 2026', status: 'planned', priority: 'high', swimlane: 'Operations' },
      { id: 'rm7', feature: 'On-Prem Decommission', description: 'Shutdown and contract termination', quarter: 'Q3 2026', status: 'planned', priority: 'medium', swimlane: 'Infrastructure' },
      { id: 'rm8', feature: 'Cost Optimization', description: 'Reserved instances, Savings Plans, right-sizing', quarter: 'Q3 2026', status: 'planned', priority: 'medium', swimlane: 'Operations' },
    ],
    governance: {
      principles: [
        'Infrastructure as Code — all AWS resources managed via Terraform',
        'Least privilege access — IAM policies follow minimal permissions',
        'Encrypt at rest and in transit — all data encrypted with AWS KMS',
        'Automated compliance — AWS Config rules enforce security standards',
        'Cost accountability — each team tagged and tracked for AWS spend',
      ],
      roles: [
        { id: 'gr1', entity: 'Steering Committee', responsibilities: 'Strategic oversight, budget approval, escalation resolution', interactions: 'Monthly review with PM, CTO', members: ['Sarah Chen', 'Marcus Williams'] },
        { id: 'gr2', entity: 'Architecture Board', responsibilities: 'Design review, technology decisions, standards enforcement', interactions: 'Bi-weekly with Lead Architect', members: ['Priya Sharma', 'AWS Consultant'] },
        { id: 'gr3', entity: 'Change Control Board', responsibilities: 'Evaluate and approve change requests', interactions: 'As needed, max 48hr turnaround', members: ['You (PM)', 'Sarah Chen', 'Priya Sharma'] },
      ],
      readinessScore: 72,
      maturityLevel: 3,
      approvedTools: [
        { id: 'at1', name: 'Terraform', purpose: 'Infrastructure as Code', guidelines: 'All infra changes via Terraform, no console clicks in production' },
        { id: 'at2', name: 'AWS CodePipeline', purpose: 'CI/CD', guidelines: 'All deployments through pipelines, no manual deploys' },
        { id: 'at3', name: 'Datadog', purpose: 'Monitoring & Alerting', guidelines: 'All services must have health checks and alerts' },
        { id: 'at4', name: 'GitHub', purpose: 'Source Control', guidelines: 'Branch protection, PR reviews required, signed commits' },
      ],
      decisionLog: [
        { id: 'dl1', date: '2026-01-20', decision: 'Use ECS Fargate instead of EC2 for containers', rationale: 'Serverless containers reduce ops overhead', madeBy: 'Architecture Board', status: 'active' },
        { id: 'dl2', date: '2026-02-05', decision: 'Multi-AZ deployment for all production workloads', rationale: 'Required for 99.99% uptime SLA', madeBy: 'Architecture Board', status: 'active' },
        { id: 'dl3', date: '2026-02-20', decision: 'Use AWS DMS for database migration', rationale: 'Supports continuous replication with minimal downtime', madeBy: 'Architecture Board', status: 'active' },
      ],
      complianceChecks: [
        { id: 'cc1', area: 'Data Encryption', requirement: 'All data encrypted at rest (SOC 2 CC6.1)', status: 'compliant', lastChecked: '2026-03-01' },
        { id: 'cc2', area: 'Access Control', requirement: 'MFA enforced for all AWS console access', status: 'compliant', lastChecked: '2026-03-01' },
        { id: 'cc3', area: 'Logging', requirement: 'CloudTrail enabled in all regions (SOC 2 CC7.2)', status: 'compliant', lastChecked: '2026-03-01' },
        { id: 'cc4', area: 'Network Security', requirement: 'VPC flow logs enabled, no public subnets for databases', status: 'partial', lastChecked: '2026-03-05' },
        { id: 'cc5', area: 'Backup & Recovery', requirement: 'Automated daily backups with 30-day retention', status: 'not-assessed', lastChecked: '' },
      ],
    },
    funding: {
      totalBudget: 450000,
      phases: [
        { id: 'fp1', name: 'Q1 — Discovery & Foundation', amount: 120000, startDate: '2026-01-15', endDate: '2026-03-31', status: 'disbursed' },
        { id: 'fp2', name: 'Q2 — Migration Execution', amount: 200000, startDate: '2026-04-01', endDate: '2026-06-30', status: 'approved' },
        { id: 'fp3', name: 'Q3 — Validation & Closure', amount: 130000, startDate: '2026-07-01', endDate: '2026-09-30', status: 'planned' },
      ],
      feasibilityNotes: 'ROI analysis shows breakeven at month 8 post-migration. Annual savings of ~$180K from infrastructure cost reduction, plus reduced ops headcount needs. AWS MAP credits offset $50K of migration costs.',
      partnerDetails: 'AWS Partner: CloudForge Solutions (Advanced Tier). Providing 2 consultants for architecture review and migration execution. Contract: $80K fixed-fee for 6 months.',
      financialProjections: 'Current on-prem: $25K/month. Projected AWS (post-optimization): $15K/month. Parallel running period (3 months): $40K/month. Total migration cost: ~$400K. Payback period: 8 months.',
    },
    stakeholders: [
      { id: 'sh1', name: 'Sarah Chen', role: 'CTO', organization: 'Executive Team', power: 5, interest: 5, engagement: 'leading', communicationPreference: 'Weekly 1:1, monthly steering committee', contactInfo: 'sarah@company.com' },
      { id: 'sh2', name: 'Marcus Williams', role: 'VP Engineering', organization: 'Engineering', power: 4, interest: 5, engagement: 'supportive', communicationPreference: 'Bi-weekly status email, Slack channel', contactInfo: 'marcus@company.com' },
      { id: 'sh3', name: 'Lisa Thompson', role: 'CFO', organization: 'Finance', power: 5, interest: 3, engagement: 'neutral', communicationPreference: 'Monthly budget report', contactInfo: 'lisa@company.com' },
      { id: 'sh4', name: 'Dev Team Leads', role: 'Engineering Leads', organization: 'Engineering', power: 3, interest: 4, engagement: 'supportive', communicationPreference: 'Sprint demos, Slack updates', contactInfo: '#eng-leads channel' },
      { id: 'sh5', name: 'Customer Success', role: 'CS Director', organization: 'Customer Success', power: 2, interest: 4, engagement: 'supportive', communicationPreference: 'Notify 2 weeks before any customer-facing changes', contactInfo: 'cs-team@company.com' },
      { id: 'sh6', name: 'Security Team', role: 'CISO', organization: 'Security', power: 4, interest: 4, engagement: 'supportive', communicationPreference: 'Security review meetings, compliance reports', contactInfo: 'security@company.com' },
    ],
    communications: [
      { id: 'cm1', type: 'meeting', name: 'Steering Committee', audience: 'CTO, VP Eng, PM', frequency: 'Monthly', owner: 'You (PM)', channel: 'Zoom', description: 'Strategic review of project health, budget, risks, and key decisions' },
      { id: 'cm2', type: 'meeting', name: 'Sprint Planning', audience: 'Migration team', frequency: 'Bi-weekly', owner: 'You (PM)', channel: 'Teams', description: 'Plan next sprint tasks, review backlog, assign work' },
      { id: 'cm3', type: 'meeting', name: 'Daily Standup', audience: 'Migration team', frequency: 'Daily', owner: 'James Park', channel: 'Slack huddle', description: '15-min sync on blockers and progress' },
      { id: 'cm4', type: 'report', name: 'Weekly Status Report', audience: 'All stakeholders', frequency: 'Weekly (Friday)', owner: 'You (PM)', channel: 'Email + Confluence', description: 'RAG status, milestones, risks, upcoming work' },
      { id: 'cm5', type: 'report', name: 'Monthly Budget Report', audience: 'CFO, CTO', frequency: 'Monthly', owner: 'You (PM)', channel: 'Email', description: 'Budget vs actual, forecast, cost optimization actions' },
      { id: 'cm6', type: 'presentation', name: 'Sprint Demo', audience: 'Stakeholders + team', frequency: 'Bi-weekly', owner: 'Dev Team', channel: 'Zoom', description: 'Demo migrated services, show progress metrics' },
    ],
    meetings: [
      {
        id: 'mt1', title: 'Steering Committee - March', date: '2026-03-05', attendees: ['Sarah Chen', 'Marcus Williams', 'You (PM)', 'Priya Sharma'],
        agenda: '1. Project status update\n2. Budget review (Q1 actuals)\n3. Risk review (VPN issue, cutover risk)\n4. Change request: Redis migration\n5. Q2 planning',
        notes: 'Sarah raised concern about VPN stability. Marcus confirmed team bandwidth for Q2. Budget tracking within 5% of plan.',
        decisions: [
          { id: 'md1', decision: 'Approved Redis migration addition to scope', madeBy: 'Sarah Chen' },
          { id: 'md2', decision: 'Allocated additional $5K for VPN troubleshooting', madeBy: 'Sarah Chen' },
        ],
        actionItems: [
          { id: 'ma1', description: 'Provide VPN root cause analysis by March 15', owner: 'Alex Rivera', dueDate: '2026-03-15', status: 'in-progress', escalateToIssue: false },
          { id: 'ma2', description: 'Update migration timeline with Redis phase', owner: 'You (PM)', dueDate: '2026-03-10', status: 'done', escalateToIssue: false },
          { id: 'ma3', description: 'Schedule EKS vs ECS decision meeting', owner: 'Priya Sharma', dueDate: '2026-03-18', status: 'open', escalateToIssue: false },
        ],
      },
      {
        id: 'mt2', title: 'Architecture Review - EKS Proposal', date: '2026-03-12', attendees: ['Priya Sharma', 'James Park', 'Alex Rivera', 'AWS Consultant'],
        agenda: '1. EKS vs ECS comparison\n2. Cost analysis\n3. Team readiness assessment\n4. Migration impact if switching',
        notes: 'Consultant recommended sticking with ECS for initial migration to avoid added complexity. Team agreed to revisit EKS post-migration as an optimization.',
        decisions: [
          { id: 'md3', decision: 'Stay with ECS Fargate for initial migration, evaluate EKS in Q4', madeBy: 'Architecture Board' },
        ],
        actionItems: [
          { id: 'ma4', description: 'Document EKS evaluation criteria for Q4 review', owner: 'Priya Sharma', dueDate: '2026-03-25', status: 'open', escalateToIssue: false },
        ],
      },
    ],
    lessons: [
      { id: 'll1', phase: 'Discovery', category: 'process', whatWorked: 'Structured application assessment template saved significant time — completed 12 apps in 3 weeks', whatDidnt: 'Initial assessment missed some infrastructure dependencies (Redis, message queues)', recommendation: 'Include infrastructure dependency mapping as a mandatory step in discovery checklist', date: '2026-02-20' },
      { id: 'll2', phase: 'Foundation', category: 'technical', whatWorked: 'Terraform modules from AWS quickstart accelerated landing zone setup', whatDidnt: 'State file management caused conflicts with multiple engineers', recommendation: 'Set up Terraform Cloud or S3 backend with DynamoDB locking from day 1', date: '2026-03-10' },
      { id: 'll3', phase: 'Foundation', category: 'people', whatWorked: 'Pair programming between team and AWS consultant accelerated learning', whatDidnt: 'Only scheduling consultant 2 days/week left gaps in knowledge transfer', recommendation: 'For critical phases, embed consultant full-time for at least 2 weeks', date: '2026-03-10' },
    ],
    decisions: [
      {
        id: 'dec-001',
        date: '2026-01-20',
        title: 'Adopt AWS EKS for Container Orchestration',
        description: 'Selected AWS EKS over self-managed Kubernetes and ECS',
        rationale: 'EKS provides managed control plane, better integration with AWS services, and reduces operational overhead. Team already has Kubernetes expertise.',
        optionsConsidered: 'Option 1: ECS (simpler but less portable), Option 2: Self-managed K8s (full control, high ops burden), Option 3: EKS (chosen - balance of control and managed services)',
        decidedBy: 'Marcus Williams (VP Eng), Priya Patel (Tech Lead)',
        impact: 'All 12 applications will be containerized and deployed via EKS. Infrastructure team needs EKS certification.',
        status: 'active',
        reviewDate: '2026-06-01',
      },
      {
        id: 'dec-002',
        date: '2026-02-05',
        title: 'Phased Migration Strategy (Lift & Shift → Optimize)',
        description: 'Decided to use lift-and-shift first, then optimize in Phase 2',
        rationale: 'Reduces risk by moving applications before re-architecting. Meets data center lease deadline.',
        optionsConsidered: 'Option 1: Big-bang re-architecture (high risk, misses deadline), Option 2: Lift & Shift only (fast but no optimization), Option 3: Phased (chosen)',
        decidedBy: 'Sarah Chen (CTO)',
        impact: 'Phase 1 completes by July 2026. Phase 2 optimization deferred to Q4 2026.',
        status: 'active',
        reviewDate: '2026-07-01',
      },
      {
        id: 'dec-003',
        date: '2026-02-28',
        title: 'Use AWS Aurora for PostgreSQL Migration',
        description: 'Replace self-hosted PostgreSQL with Amazon Aurora PostgreSQL-Compatible',
        rationale: 'Aurora provides 5x throughput, automated backups, multi-AZ failover. Cost analysis shows comparable to self-managed at scale.',
        optionsConsidered: 'RDS PostgreSQL vs Aurora PostgreSQL vs self-managed EC2. Aurora chosen for performance and HA.',
        decidedBy: 'Priya Patel, James Kim (DBA Lead)',
        impact: 'Database migration adds 2 weeks to schedule. Requires Aurora-specific connection string updates.',
        status: 'active',
        reviewDate: '2026-05-01',
      },
    ],
    assumptions: [
      {
        id: 'assum-001',
        assumption: 'AWS account and landing zone will be provisioned by IT Ops by February 1, 2026',
        category: 'technical',
        owner: 'James Kim',
        validationMethod: 'IT Ops confirmation email + AWS console access test',
        targetValidationDate: '2026-02-01',
        validationStatus: 'validated',
        impactIfInvalid: 'Migration cannot begin. Delays entire project by 3-4 weeks.',
        riskLevel: 'critical',
        notes: 'Validated on 2026-01-28. Account provisioned and landing zone configured.',
      },
      {
        id: 'assum-002',
        assumption: 'Development team has or will obtain basic AWS certification before Phase 2',
        category: 'resource',
        owner: 'Priya Patel',
        validationMethod: 'Track AWS certification progress via HR system',
        targetValidationDate: '2026-04-01',
        validationStatus: 'in-progress',
        impactIfInvalid: 'Team cannot independently operate AWS infrastructure. Need external support or training delay.',
        riskLevel: 'high',
        notes: '4 of 8 devs have completed AWS Cloud Practitioner. 2 are in progress. 2 not started.',
      },
      {
        id: 'assum-003',
        assumption: 'All 12 applications support containerization without major refactoring',
        category: 'technical',
        owner: 'Priya Patel',
        validationMethod: 'Container compatibility assessment report per application',
        targetValidationDate: '2026-02-15',
        validationStatus: 'invalidated',
        impactIfInvalid: 'Legacy App #7 (billing system) requires 6 weeks of refactoring. RISK-003 raised.',
        riskLevel: 'critical',
        notes: 'Assessment complete. 11 of 12 apps containerizable. Billing system (App #7) requires refactoring - old COM dependencies.',
      },
      {
        id: 'assum-004',
        assumption: 'Data center will extend lease through October 2026 if migration overruns',
        category: 'business',
        owner: 'Sarah Chen',
        validationMethod: 'Written confirmation from facilities/legal',
        targetValidationDate: '2026-03-01',
        validationStatus: 'unvalidated',
        impactIfInvalid: 'Hard deadline - migration must complete by September 30, 2026.',
        riskLevel: 'high',
        notes: 'Awaiting legal team response on lease extension clause.',
      },
    ],
    statusReports: [
      {
        id: 'sr-001',
        reportDate: '2026-03-13',
        reportingPeriod: 'Week of March 9-13, 2026',
        preparedBy: 'Kwame Mensah',
        overallStatus: 'amber',
        executiveSummary: 'AWS Cloud Migration is progressing at 58% overall completeness. Phase 1 (Discovery & Assessment) is complete. Phase 2 (Architecture Design) is on track. A critical risk materialized this week: the billing system (App #7) requires 6 weeks of refactoring due to COM dependencies, which threatens the September deadline. Mitigation plan is in place.',
        accomplishments: [
          'Completed containerization assessment for all 12 applications',
          'AWS EKS cluster deployed in staging environment',
          'Aurora PostgreSQL migration tested successfully with 99.8% data fidelity',
          'IAM roles and security policies finalized and reviewed by security team',
        ],
        nextPeriodPlans: [
          'Begin billing system refactoring (App #7) - assign 2 additional developers',
          'Complete network architecture design for VPC peering',
          'Kick off CI/CD pipeline setup for first 3 applications',
          'Schedule disaster recovery runbook review with ops team',
        ],
        risks: 'RISK-004 (Billing System Refactoring) escalated to HIGH. Mitigation: additional developers assigned, 2-week buffer added to schedule. RISK-002 (Data Loss During Migration) remains MEDIUM - Aurora snapshots configured.',
        issues: 'ISSUE-002 (Legacy Dependencies in App #7) is BLOCKED - billing system cannot be containerized as-is. Unblocking by assigning dedicated refactoring sprint starting March 16.',
        budgetStatus: 'Spent $187,000 of $450,000 (41.6%). On track. Next major spend: EKS node group scaling in Phase 3.',
        scheduleStatus: 'AMBER. Overall on track but App #7 refactoring adds risk to September 30 deadline. Critical path updated. 2-week contingency buffer activated.',
        aiGenerated: false,
      },
    ],
    actionItems: [],
    auditLog: [],
    baselines: [],
  };
}
